package org.codepulsar.pulsar;

public enum TokenType {
    // Operators
    TK_NOT, TK_PLUSPLUS, TK_MINUSMINUS, // Unary
    TK_MINUS, TK_PLUS, TK_MULTIPLICATION, TK_DIVISION, TK_MODULUS, // Binary
    TK_NOTEQUAL, TK_EQUALEQUAL, TK_GT, TK_GTEQUAL, TK_LT, TK_LTEQUAL, // Comparison
    TK_EQUAL, TK_PLUSEQUAL, TK_MINUSEQUAL, TK_MULEQUAL, TK_DIVEQUAL, TK_MODEQUAL, // Assignment
    TK_LOGICALOR, TK_LOGICALAND, // Logical

    // Other Character Tokens
    TK_DOT, TK_COMMA, TK_COLON, TK_SEMICOLON, TK_DOUBLECOLON, TK_QMARK,
    TK_LPAR, TK_RPAR, TK_LBRACE, TK_RBRACE,

    // Keywords
    TK_PACKAGE, TK_USE, TK_MOD, TK_CLASS,
    TK_VAR, TK_CONST,
    TK_FUN, TK_RETURN,
    TK_IF, TK_ELSE, TK_WHILE,

    // Data Types and Variables
    TK_STRING, TK_INTEGER, TK_DOUBLE, TK_IDENTIFIER, TK_TRUE, TK_FALSE,

    // Special Tokens
    TK_ERROR, TK_EOF
}
